# Generated by Django 5.2 on 2025-05-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_size', models.CharField(choices=[('short', '1.5м - 3.6м'), ('wide', '4.0м - 5.0м'), ('the widest', '5.8м')], max_length=20, verbose_name='Размер ткани')),
                ('ceiling_type', models.CharField(choices=[('white mat', 'Белый мат'), ('colored mat', 'Цветной мат'), ('white gloss', 'Белый лак'), ('colored gloss', 'Цветной лак'), ('white sateen', 'Белый сатин'), ('colored sateen', 'Цветной сатин'), ('venice', 'Венеция'), ('sky', 'Небо')], max_length=20, verbose_name='Тип потолка')),
                ('price_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за м²')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка цены',
                'verbose_name_plural': 'Настройки цен',
                'unique_together': {('fabric_size', 'ceiling_type', 'user')},
            },
        ),
    ]
