# Generated by Django 5.2 on 2025-06-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_priceaccessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceaccessories',
            options={'verbose_name': 'Настройка цены комплектующих', 'verbose_name_plural': 'Настройки цен комплектующих'},
        ),
    ]
