# Generated by Django 6.0 on 2026-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_priceaccessories_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceaccessories',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pricesettings',
            name='price_m2',
        ),
        migrations.AddField(
            model_name='priceaccessories',
            name='bought',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Купил за'),
        ),
        migrations.AddField(
            model_name='priceaccessories',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наценка'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='bought',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Купил за м²'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наценка за м²'),
        ),
    ]
