# Generated by Django 5.2 on 2025-05-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fabric_size', models.CharField(choices=[('short', '1.5м - 3.6м'), ('wide', '4.0м - 5.0м'), ('the widest', '5.8м')], max_length=10)),
                ('ceiling_type', models.CharField(choices=[('white mat', 'Белый мат'), ('colored mat', 'Цветной мат'), ('white gloss', 'Белый лак'), ('colored gloss', 'Цветной лак'), ('white sateen', 'Белый сатин'), ('colored sateen', 'Цветной сатин'), ('venice', 'Венеция'), ('sky', 'Небо')], max_length=14)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='order_photos/')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Завершен')], default='new', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено')], default='unpaid', max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
