# Generated by Django 5.2 on 2025-06-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_status_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Количество'),
        ),
    ]
