# Generated by Django 5.2 on 2025-06-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_accessories_quantity'),
        ('settings', '0004_alter_priceaccessories_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='name',
        ),
        migrations.AddField(
            model_name='accessories',
            name='accessories',
            field=models.ForeignKey(blank=True, limit_choices_to={'user': models.F('user')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories_orders', to='settings.priceaccessories', verbose_name='Комплектующий'),
        ),
    ]
