# Generated by Django 5.2 on 2025-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_accessories_name_accessories_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default='2002-11-03'),
            preserve_default=False,
        ),
    ]
