# Generated by Django 5.2 on 2025-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessories',
            name='payment_status',
            field=models.CharField(choices=[('not paid', 'Не оплачено'), ('paid', 'Оплачено')], default='not paid', max_length=15),
        ),
    ]
