# Generated by Django 5.2 on 2025-10-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_accessories_completed_at_accessories_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='completed_at',
        ),
    ]
